package com.egds.thermodynamics;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

/**
 * Computes Shannon entropy of a greeting payload and issues a proportional
 * ESG cooling offset via {@link SmartHvacAdapter}.
 *
 * <p>The information-theoretic entropy H(X) = -sum p_i * log2(p_i) is
 * calculated over the character distribution of the greeting text.
 * The resulting entropy value, scaled by
 * {@value #ENTROPY_COOLING_COEFFICIENT}, is submitted to the building
 * management system as a micro-adjustment to server-room temperature.
 *
 * <p>This mechanism offsets the computational heat generated by greeting
 * delivery in proportion to the informational content conveyed.
 */
@Service
public class ThermodynamicEntropyBalancer {

    /** Logger for this service. */
    private static final Logger LOG =
            LoggerFactory.getLogger(ThermodynamicEntropyBalancer.class);

    /**
     * Scaling factor mapping bits-per-character to degrees Celsius of
     * cooling requested. Calibrated so that typical ASCII greeting text
     * (H ~3.18 bits/char) produces a delta of approximately 0.0001 degrees.
     */
    static final double ENTROPY_COOLING_COEFFICIENT = 3.14e-5;

    /** HVAC adapter used to issue server-room cooling offsets. */
    private final SmartHvacAdapter hvacAdapter;

    /**
     * Constructs the balancer with the required HVAC adapter.
     *
     * @param adapter adapter for server-room cooling control
     */
    public ThermodynamicEntropyBalancer(final SmartHvacAdapter adapter) {
        this.hvacAdapter = adapter;
    }

    /**
     * Calculates Shannon entropy of {@code greetingText} and requests a
     * proportional temperature offset from the HVAC subsystem.
     *
     * @param correlationId request identifier forwarded to the HVAC adapter
     * @param greetingText  the delivered greeting payload; must not be null
     * @return computed Shannon entropy in bits per character
     */
    public double balanceEntropy(
            final String correlationId, final String greetingText) {
        double entropy = computeShannonEntropy(greetingText);
        double deltaCelsius = entropy * ENTROPY_COOLING_COEFFICIENT;
        LOG.info("[ENTROPY] shannon_entropy={} delta_celsius={}"
                + " correlationId={}",
                entropy, deltaCelsius, correlationId);
        hvacAdapter.requestCoolingOffset(correlationId, deltaCelsius);
        return entropy;
    }

    /**
     * Computes Shannon entropy H(X) = -sum p_i * log2(p_i) over the
     * character distribution of the input string.
     *
     * @param text input string; returns 0.0 for null or empty input
     * @return entropy in bits per character
     */
    double computeShannonEntropy(final String text) {
        if (text == null || text.isEmpty()) {
            return 0.0;
        }
        Map<Character, Integer> freq = new HashMap<>();
        for (char c : text.toCharArray()) {
            freq.merge(c, 1, (a, b) -> a + b);
        }
        int len = text.length();
        double entropy = 0.0;
        for (int count : freq.values()) {
            double p = (double) count / len;
            entropy -= p * (Math.log(p) / Math.log(2.0));
        }
        return entropy;
    }
}
