package com.egds.ai;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.concurrent.ConcurrentHashMap;

/**
 * Mock adapter for Terraform-driven ephemeral AWS Lambda provisioning.
 *
 * <p>Each greeting request triggers a full infrastructure lifecycle:
 * provision, invoke, destroy. In production, this adapter would spawn a
 * child process executing {@code terraform apply} against a real AWS
 * provider configuration, obtain the deployed function ARN from the
 * Terraform output, invoke the function via the AWS SDK, then run
 * {@code terraform destroy} to remove all provisioned resources.
 *
 * <p>In this implementation the Terraform CLI is mocked; no external
 * process is spawned and no AWS credentials are required.
 */
@Service
public class EphemeralTerraformAdapter {

    /** Logger for this class. */
    private static final Logger LOG =
            LoggerFactory.getLogger(EphemeralTerraformAdapter.class);

    /** ARN template for provisioned ephemeral Lambda functions. */
    private static final String LAMBDA_ARN_TEMPLATE =
            "arn:aws:lambda:us-east-1:000000000000:function:egds-ephemeral-%s";

    /** Maximum number of characters taken from the correlation ID suffix. */
    private static final int ARN_SUFFIX_LENGTH = 12;

    /** Tracks active ephemeral deployments by correlationId. */
    private final ConcurrentHashMap<String, String> activeDeployments =
            new ConcurrentHashMap<>();

    /**
     * Simulates {@code terraform apply} to provision a single-use Lambda.
     *
     * @param correlationId unique identifier for this greeting request
     * @return the mock ARN of the provisioned Lambda function
     */
    public String provision(final String correlationId) {
        String suffix = correlationId.replace("-", "");
        String lambdaArn = String.format(LAMBDA_ARN_TEMPLATE,
                suffix.substring(
                        0, Math.min(ARN_SUFFIX_LENGTH, suffix.length())));
        activeDeployments.put(correlationId, lambdaArn);
        LOG.info("[TERRAFORM] apply complete correlationId={} arn={}",
                correlationId, lambdaArn);
        return lambdaArn;
    }

    /**
     * Simulates invoking the provisioned Lambda function.
     *
     * <p>In production this would issue an AWS SDK {@code InvokeRequest}
     * to the function ARN returned by {@link #provision(String)} and
     * deserialise the response payload. The mock returns the supplied
     * greeting unchanged, representing a Lambda function whose sole
     * purpose is to echo the greeting generated by the upstream LLM.
     *
     * @param lambdaArn the ARN of the provisioned function
     * @param greeting  the greeting payload forwarded to the Lambda
     * @return the greeting as returned by the mock Lambda invocation
     */
    public String invoke(final String lambdaArn, final String greeting) {
        LOG.info("[TERRAFORM] lambda invoked arn={} payload_len={}",
                lambdaArn, greeting.length());
        return greeting;
    }

    /**
     * Simulates {@code terraform destroy} to remove the ephemeral Lambda
     * and all associated IAM roles, log groups, and VPC resources.
     *
     * @param correlationId the correlationId whose infrastructure is to be
     *                      destroyed
     */
    public void destroy(final String correlationId) {
        String removed = activeDeployments.remove(correlationId);
        if (removed != null) {
            LOG.info("[TERRAFORM] destroy complete correlationId={} arn={}",
                    correlationId, removed);
        } else {
            LOG.warn("[TERRAFORM] destroy called for unknown deployment"
                    + " correlationId={}", correlationId);
        }
    }

    /**
     * Returns the number of currently active (not yet destroyed) deployments.
     *
     * @return active deployment count
     */
    public int activeDeploymentCount() {
        return activeDeployments.size();
    }
}
